// <auto-generated />
namespace HiNSimulator2014.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lagttilaccesslevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lagttilaccesslevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201411051222595_lagt til accesslevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
