// <auto-generated />
namespace HiNSimulator2014.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class nyefelter2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nyefelter2));
        
        string IMigrationMetadata.Id
        {
            get { return "201411200959363_nyefelter2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
